name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 */1 *'

jobs:
  build:
    # colobot-lint builds only with LLVM 3.6 and later Ubuntu versions don't have it in the repo
    runs-on: ubuntu-16.04
    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends llvm-3.6-dev libclang-3.6.dev libtinyxml-dev libboost-regex-dev libncurses-dev
    - uses: actions/checkout@v2
    - name: Create build directory
      run: cmake -E make_directory build
    - name: Run cmake
      working-directory: build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=1 -DCMAKE_CXX_FLAGS="-I/usr/lib/llvm-3.6/include -L/usr/lib/llvm-3.6/lib" ..
    - name: Build
      working-directory: build
      run: cmake --build . -j `nproc`
    - name: Package HtmlReport
      run: tar -zcf build/html_report.tar.gz HtmlReport/
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: colobot-lint
        path: |
          build/colobot-lint
          build/html_report.tar.gz
          Tools/count_errors.py
    - name: Run tests
      working-directory: build
      run: ctest --no-compress-output -T Test .
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Test results
        path: build/Testing/**/Test.xml
      if: always()
